### ISSUE TITLE
noportals:disabled.end instead of normal translationed string

### ISSUE THREAD

**Issue by Philainel** [kevinthegreat1/NoPortals-Fabric#4]
![2023-05-20_20 12 47](https://github.com/kevinthegreat1/NoPortals-Fabric/assets/53627523/3d907c65-30aa-4015-8da0-fa34ffc58179)

The actionbar title show translation key instead of translationed string.

Minecraft version: 1.19.4, Mod version: 1.0.1, Fabric API: 0.80.0, Fabric loader: 0.14.19

**Comment by kevinthegreat1** [comment]
You need the mod installed on the client for text to work.

**Comment by Philainel** [comment]
Oh, that would be excelent feature

**Comment by Rozbiynk** [comment]
is there way to change it for hardcoded value?

**Comment by kevinthegreat1** [comment]
Server translations added in version 1.10.

**Comment by Rozbiynk** [comment]
do you plan backport it to 1.20.1?

**Comment by Rozbiynk** [comment]
do you plan 1.20.1 version?
