### ISSUE TITLE
UnsupportedClassVersionError

### ISSUE THREAD

**Issue by eslicarrillo** [kevinthegreat1/NoPortals-Fabric#6]
The last update causes the following error

net.fabricmc.loader.impl.FormattedException: java.lang.UnsupportedClassVersionError: net/minecraft/class_2423 has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0

**Comment by kevinthegreat1** [comment]
Marked the latest version as 1.20.5 and 1.20.6 only.
