### ISSUE TITLE
Server Translation API not working

### ISSUE THREAD

**Issue by GhostGamerMC** [kevinthegreat1/NoPortals-Fabric#9]
The Mod doesn't work on 1.21.3 Fabric:
Would it be posslible to just ignore the Server-Translation-API and use this Mod without it.
Error Code: java.lang.AbstractMethodError: Receiver class xyz.nucleoid.server.translations.impl.ServerTranslations does not define or inherit an implementation of the resolved method 'abstract java.util.concurrent.CompletableFuture method_25931(net.minecraft.class_3302$class_4045, net.minecraft.class_3300, java.util.concurrent.Executor, java.util.concurrent.Executor)' of interface net.minecraft.class_3302.

**Comment by kevinthegreat1** [comment]
Just had to update server translation api, fixed in version 1.1.4.
